name: HugotoGhpages
on: [push]
jobs:
  build:
    runs-on: testgitrunner1
    steps:
      - name: "clone"
        run: |
          rm -fr *
          git clone git@github.com:asrarparveenkp/hugoghpages.git updateBranch
      
